packages:
  - "packages/*"
  - "packages/eslint-config/*"
  - "apps/*"

catalog:
  "@cspell/eslint-plugin": 9.0.2
  "@eslint/compat": 1.2.9
  "@eslint/eslintrc": 3.3.1
  "@eslint/js": 9.27.0
  "@eslint/json": 0.12.0
  "@eslint/markdown": 6.4.0
  "@typescript-eslint/eslint-plugin": 8.32.1
  "@typescript-eslint/parser": 8.32.1
  "eslint-config-prettier": 10.1.5
  "eslint-plugin-import": 2.31.0
  "eslint-plugin-react-hooks": 5.2.0
  "eslint-plugin-turbo": 2.5.3
  "eslint-plugin-unicorn": 59.0.1
  "eslint-plugin-unused-imports": 4.1.4
  "globals": 16.2.0
  "typescript-eslint": 8.32.1
  "@types/eslint-config-prettier": 6.11.3
  "@types/node": 22.15.21
  "@typescript-eslint/utils": 8.32.1
  "rolldown": 1.0.0-beta.9
  "tsup": 8.5.0
  "tsx": 4.19.4
  "typescript": 5.8.3
  "@next/eslint-plugin-next": 15.3.2
  "eslint-config-next": 15.3.2
  "eslint-plugin-storybook": 0.12.0
  "eslint-plugin-astro": 1.3.1
