packages:
  - packages/*
  - packages/eslint-config/*
  - apps/*

catalog:
  '@astrojs/cloudflare': 12.6.12
  '@astrojs/react': 4.4.2
  '@astrojs/solid-js': 5.1.3
  '@crxjs/vite-plugin': 2.2.1
  '@cspell/cspell-types': 9.4.0
  '@cspell/eslint-plugin': 9.4.0
  '@eslint/compat': 2.0.0
  '@eslint/config-inspector': 1.4.2
  '@eslint/eslintrc': 3.3.3
  '@eslint/js': 9.39.1
  '@eslint/json': 0.14.0
  '@eslint/markdown': 7.5.1
  '@formkit/tempo': 0.1.2
  '@heroicons/react': 2.2.0
  '@hookform/resolvers': 5.2.2
  '@lerna-lite/cli': 4.9.4
  '@lerna-lite/publish': 4.9.4
  '@lerna-lite/version': 4.9.4
  '@next-auth/prisma-adapter': 1.0.7
  '@next/eslint-plugin-next': 16.0.6
  '@prisma/client': 7.0.1
  '@radix-ui/colors': 3.0.0
  '@radix-ui/react-aspect-ratio': 1.1.8
  '@radix-ui/react-avatar': 1.1.11
  '@radix-ui/react-form': 0.1.8
  '@radix-ui/react-progress': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@stitches/react': 1.2.8
  '@storybook/addon-actions': 9.0.8
  '@storybook/addon-docs': 10.1.3
  '@storybook/addon-essentials': 8.6.14
  '@storybook/addon-interactions': 8.6.14
  '@storybook/addon-links': 10.1.3
  '@storybook/addon-styling-webpack': 3.0.0
  '@storybook/blocks': 8.6.14
  '@storybook/nextjs': 10.1.3
  '@storybook/react': 10.1.3
  '@storybook/react-vite': 10.1.3
  '@storybook/react-webpack5': 10.1.3
  '@storybook/test': 8.6.14
  '@tailwindcss/forms': 0.5.10
  '@tailwindcss/postcss': 4.1.17
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.0
  '@testing-library/user-event': 14.6.1
  '@turbo/gen': 2.6.1
  '@types/bcrypt': 6.0.0
  '@types/chrome': 0.1.32
  '@types/eslint-config-prettier': 6.11.3
  '@types/jest': 30.0.0
  '@types/jsdom': 27.0.0
  '@types/mock-fs': 4.13.4
  '@types/node': 24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@typescript-eslint/eslint-plugin': 8.48.0
  '@typescript-eslint/parser': 8.48.0
  '@typescript-eslint/utils': 8.48.0
  '@unocss/reset': 66.5.9
  '@vanilla-extract/css': 1.17.5
  '@vanilla-extract/dynamic': 2.1.5
  '@vanilla-extract/next-plugin': 2.4.16
  '@vanilla-extract/webpack-plugin': 2.3.24
  '@vercel/postgres': 0.10.0
  '@vitejs/plugin-react': 5.1.1
  '@vitest/ui': 4.0.14
  astro: 5.16.3
  autoprefixer: 10.4.22
  bcrypt: 6.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  consola: 3.4.2
  cpx2: 8.0.0
  cspell: 9.4.0
  css-loader: 7.1.2
  dotenv: 17.2.3
  dotenv-cli: 11.0.0
  effect: 3.19.8
  es-toolkit: 1.42.0
  esbuild: 0.27.0
  eslint: 9.39.1
  eslint-config-next: 16.0.6
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-astro: 1.5.0
  eslint-plugin-import: 2.32.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-only-warn: 1.1.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-storybook: 10.1.3
  eslint-plugin-turbo: 2.6.1
  eslint-plugin-unicorn: 62.0.0
  eslint-plugin-unused-imports: 4.3.0
  eslint-plugin-yml: 1.19.0
  eslint-typegen: 2.3.0
  evp-ts: 1.1.1
  fs-extra: 11.3.2
  get-windows: 9.2.3
  git-cz: 4.9.0
  glob: 13.0.0
  globals: 16.5.0
  gsap: 3.13.0
  header-inserter: 1.0.30
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  jest-html-reporters: 3.1.7
  jotai: 2.15.2
  jsdom: 27.2.0
  lucide-react: 0.555.0
  mini-css-extract-plugin: 2.9.4
  msw: 2.12.3
  neverthrow: 8.2.0
  next: 16.0.6
  next-auth: 4.24.13
  next-themes: 0.4.6
  node-fetch: 3.3.2
  npm-run-all2: 8.0.4
  pino: 10.1.0
  postcss: 8.5.6
  prettier: 3.7.3
  prisma: 7.0.1
  puppeteer: 24.31.0
  react: 19.2.0
  react-dom: 19.2.0
  react-hook-form: 7.67.0
  react-lite-youtube-embed: 3.3.3
  react-tweet: 3.2.2
  recharts: 3.5.1
  renovate: 42.29.4
  schema-dts: 1.1.5
  serve: 14.2.5
  solid-js: 1.9.10
  storybook: 10.1.3
  style-loader: 4.0.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  textlint: 15.4.0
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.2.2
  textlint-rule-no-todo: 2.0.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  ts-jest: 29.4.6
  tsconfig-paths-webpack-plugin: 4.2.0
  tsdown: 0.16.8
  tsup: 8.5.1
  tsx: 4.21.0
  turbo: 2.6.1
  tw-animate-css: 1.4.0
  type-fest: 5.2.0
  typescript: 5.9.3
  typescript-eslint: 8.48.0
  unocss: 66.5.9
  valibot: 1.2.0
  vercel: 48.12.0
  vite: 7.2.6
  vitest: 4.0.14
  webpack-merge: 6.0.1
  wrangler: 4.51.0
  zod: 4.1.13
