packages:
  - packages/*
  - packages/eslint-config/*
  - apps/*

catalog:
  '@astrojs/cloudflare': 12.6.8
  '@astrojs/react': 4.3.1
  '@astrojs/solid-js': 5.1.1
  '@crxjs/vite-plugin': 2.2.0
  '@cspell/cspell-types': 9.2.1
  '@cspell/eslint-plugin': 9.2.1
  '@eslint/compat': 1.3.2
  '@eslint/config-inspector': 1.2.0
  '@eslint/eslintrc': 3.3.1
  '@eslint/js': 9.35.0
  '@eslint/json': 0.13.2
  '@eslint/markdown': 7.2.0
  '@formkit/tempo': 0.1.2
  '@heroicons/react': 2.2.0
  '@hookform/resolvers': 5.2.1
  '@lerna-lite/cli': 4.7.3
  '@lerna-lite/publish': 4.7.3
  '@lerna-lite/version': 4.7.3
  '@next-auth/prisma-adapter': 1.0.7
  '@next/eslint-plugin-next': 15.5.3
  '@prisma/client': 6.16.1
  '@radix-ui/colors': 3.0.0
  '@radix-ui/react-aspect-ratio': 1.1.7
  '@radix-ui/react-avatar': 1.1.10
  '@radix-ui/react-form': 0.1.8
  '@radix-ui/react-progress': 1.1.7
  '@radix-ui/react-slot': 1.2.3
  '@stitches/react': 1.2.8
  '@storybook/addon-actions': 9.0.8
  '@storybook/addon-docs': 9.1.5
  '@storybook/addon-essentials': 8.6.14
  '@storybook/addon-interactions': 8.6.14
  '@storybook/addon-links': 9.1.5
  '@storybook/addon-styling-webpack': 2.0.0
  '@storybook/blocks': 8.6.14
  '@storybook/nextjs': 9.1.5
  '@storybook/react': 9.1.5
  '@storybook/react-vite': 9.1.5
  '@storybook/test': 8.6.14
  '@tailwindcss/forms': 0.5.10
  '@tailwindcss/postcss': 4.1.13
  '@testing-library/jest-dom': 6.8.0
  '@testing-library/react': 16.3.0
  '@testing-library/user-event': 14.6.1
  '@turbo/gen': 2.5.6
  '@types/bcrypt': 6.0.0
  '@types/chrome': 0.1.9
  '@types/eslint-config-prettier': 6.11.3
  '@types/jest': 30.0.0
  '@types/jsdom': 21.1.7
  '@types/mock-fs': 4.13.4
  '@types/node': 22.18.1
  '@types/react': 19.1.12
  '@types/react-dom': 19.1.9
  '@typescript-eslint/eslint-plugin': 8.43.0
  '@typescript-eslint/parser': 8.43.0
  '@typescript-eslint/utils': 8.43.0
  '@unocss/reset': 66.5.1
  '@vanilla-extract/css': 1.17.4
  '@vanilla-extract/dynamic': 2.1.5
  '@vanilla-extract/next-plugin': 2.4.14
  '@vanilla-extract/webpack-plugin': 2.3.22
  '@vercel/postgres': 0.10.0
  '@vitejs/plugin-react': 5.0.2
  '@vitest/ui': 3.2.4
  astro: 5.13.7
  autoprefixer: 10.4.21
  bcrypt: 6.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  consola: 3.4.2
  cpx2: 8.0.0
  cspell: 9.2.1
  css-loader: 7.1.2
  dotenv: 17.2.2
  dotenv-cli: 10.0.0
  effect: 3.17.13
  es-toolkit: 1.39.10
  esbuild: 0.25.9
  eslint: 9.35.0
  eslint-config-next: 15.5.3
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-astro: 1.3.1
  eslint-plugin-import: 2.32.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-only-warn: 1.1.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-storybook: 9.1.5
  eslint-plugin-turbo: 2.5.6
  eslint-plugin-unicorn: 61.0.2
  eslint-plugin-unused-imports: 4.2.0
  eslint-plugin-yml: 1.18.0
  eslint-typegen: 2.3.0
  evp-ts: 1.1.1
  fs-extra: 11.3.1
  get-windows: 9.2.3
  git-cz: 4.9.0
  glob: 11.0.3
  globals: 16.4.0
  gsap: 3.13.0
  header-inserter: 1.0.28
  jest: 30.1.3
  jest-environment-jsdom: 30.1.2
  jest-html-reporters: 3.1.7
  jotai: 2.14.0
  jsdom: 26.1.0
  lucide-react: 0.544.0
  mini-css-extract-plugin: 2.9.4
  msw: 2.11.2
  neverthrow: 8.2.0
  next: 15.5.3
  next-auth: 4.24.11
  next-themes: 0.4.6
  node-fetch: 3.3.2
  npm-run-all2: 8.0.4
  pino: 9.9.5
  postcss: 8.5.6
  prettier: 3.6.2
  prisma: 6.16.1
  puppeteer: 24.20.0
  react: 19.1.1
  react-dom: 19.1.1
  react-hook-form: 7.62.0
  react-lite-youtube-embed: 2.5.6
  react-tweet: 3.2.2
  recharts: 3.2.0
  renovate: 41.99.9
  schema-dts: 1.1.5
  serve: 14.2.5
  solid-js: 1.9.9
  storybook: 9.1.5
  style-loader: 4.0.0
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.13
  textlint: 15.2.2
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.2.2
  textlint-rule-no-todo: 2.0.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  ts-jest: 29.4.1
  tsconfig-paths-webpack-plugin: 4.2.0
  tsdown: 0.15.0
  tsup: 8.5.0
  tsx: 4.20.5
  turbo: 2.5.6
  tw-animate-css: 1.3.8
  type-fest: 4.41.0
  typescript: 5.9.2
  typescript-eslint: 8.43.0
  unocss: 66.5.1
  valibot: 1.1.0
  vercel: 47.1.3
  vite: 7.1.5
  vitest: 3.2.4
  webpack-merge: 6.0.1
  wrangler: 4.35.0
  zod: 4.1.7
