packages:
  - packages/*
  - packages/eslint-config/*
  - apps/*

catalog:
  '@astrojs/cloudflare': 12.6.12
  '@astrojs/react': 4.4.2
  '@astrojs/solid-js': 5.1.3
  '@crxjs/vite-plugin': 2.3.0
  '@cspell/cspell-types': 9.6.4
  '@cspell/eslint-plugin': 9.6.4
  '@eslint/compat': 2.0.2
  '@eslint/config-inspector': 1.4.2
  '@eslint/eslintrc': 3.3.3
  '@eslint/js': 9.39.2
  '@eslint/json': 1.0.1
  '@eslint/markdown': 7.5.1
  '@formkit/tempo': 1.0.0
  '@hookform/resolvers': 5.2.2
  '@lerna-lite/cli': 4.11.2
  '@lerna-lite/publish': 4.11.2
  '@lerna-lite/version': 4.11.2
  '@next-auth/prisma-adapter': 1.0.7
  '@next/eslint-plugin-next': 16.1.6
  '@playwright/test': 1.58.2
  '@prisma/client': 7.4.0
  '@radix-ui/colors': 3.0.0
  '@radix-ui/react-aspect-ratio': 1.1.8
  '@radix-ui/react-avatar': 1.1.11
  '@radix-ui/react-form': 0.1.8
  '@radix-ui/react-progress': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@stitches/react': 1.2.8
  '@storybook/addon-actions': 9.0.8
  '@storybook/addon-docs': 10.2.8
  '@storybook/addon-essentials': 8.6.14
  '@storybook/addon-interactions': 8.6.14
  '@storybook/addon-links': 10.2.8
  '@storybook/addon-styling-webpack': 3.0.0
  '@storybook/blocks': 8.6.14
  '@storybook/nextjs': 10.2.8
  '@storybook/react': 10.2.8
  '@storybook/react-vite': 10.2.8
  '@storybook/react-webpack5': 10.2.8
  '@storybook/test': 8.6.15
  '@tailwindcss/postcss': 4.1.18
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.2
  '@testing-library/user-event': 14.6.1
  '@turbo/gen': 2.8.9
  '@types/bcrypt': 6.0.0
  '@types/chrome': 0.1.36
  '@types/eslint-config-prettier': 6.11.3
  '@types/jest': 30.0.0
  '@types/jsdom': 27.0.0
  '@types/mock-fs': 4.13.4
  '@types/node': 24.10.13
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@typescript-eslint/eslint-plugin': 8.55.0
  '@typescript-eslint/parser': 8.55.0
  '@unocss/reset': 66.6.0
  '@vanilla-extract/css': 1.18.0
  '@vanilla-extract/dynamic': 2.1.5
  '@vanilla-extract/next-plugin': 2.4.17
  '@vanilla-extract/webpack-plugin': 2.3.25
  '@vitejs/plugin-react': 5.1.4
  '@vitest/ui': 4.0.18
  astro: 5.17.2
  autoprefixer: 10.4.24
  capnp-es: 0.0.14
  bcrypt: 6.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  consola: 3.4.2
  cspell: 9.6.4
  css-loader: 7.1.3
  dotenv: 17.3.1
  dotenv-cli: 11.0.0
  effect: 3.19.17
  es-toolkit: 1.44.0
  eslint: 9.39.2
  eslint-config-next: 16.1.6
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-astro: 1.6.0
  eslint-plugin-import: 2.32.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-only-warn: 1.1.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-storybook: 10.2.8
  eslint-plugin-turbo: 2.8.9
  eslint-plugin-unicorn: 63.0.0
  eslint-plugin-unused-imports: 4.4.1
  eslint-plugin-yml: 3.1.2
  eslint-typegen: 2.3.0
  evp-ts: 1.1.1
  fs-extra: 11.3.3
  get-windows: 9.2.3
  git-cz: 4.9.0
  glob: 13.0.3
  globals: 17.3.0
  gsap: 3.14.2
  header-inserter: 1.0.31
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  jest-html-reporters: 3.1.7
  jiti: 2.6.1
  jotai: 2.17.1
  jsdom: 28.0.0
  lucide-react: 0.564.0
  mini-css-extract-plugin: 2.10.0
  msw: 2.12.10
  neverthrow: 8.2.0
  next: 16.1.6
  next-auth: 4.24.13
  next-themes: 0.4.6
  node-fetch: 3.3.2
  npm-run-all2: 8.0.4
  pino: 10.3.1
  playwright: 1.58.2
  postcss: 8.5.6
  prettier: 3.8.1
  prisma: 7.4.0
  puppeteer: 24.37.3
  react: 19.2.4
  react-dom: 19.2.4
  react-hook-form: 7.71.1
  react-lite-youtube-embed: 3.3.3
  react-tweet: 3.3.0
  recharts: 3.7.0
  renovate: 43.14.1
  schema-dts: 1.1.5
  serve: 14.2.5
  solid-js: 1.9.11
  storybook: 10.2.8
  style-loader: 4.0.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tap: 21.5.1
  textlint: 15.5.1
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.3.0
  textlint-rule-no-todo: 2.0.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  ts-jest: 29.4.6
  tsconfig-paths-webpack-plugin: 4.2.0
  tsdown: 0.20.3
  tsx: 4.21.0
  turbo: 2.8.9
  tw-animate-css: 1.4.0
  type-fest: 5.4.4
  typescript: 5.9.3
  typescript-eslint: 8.55.0
  unocss: 66.6.0
  valibot: 1.2.0
  vercel: 50.17.1
  vite: 7.3.1
  vitest: 4.0.18
  webpack-merge: 6.0.1
  wrangler: 4.65.0
  zod: 4.3.6
