packages:
  - packages/*
  - packages/eslint-config/*
  - apps/*

catalog:
  "@astrojs/react": 4.3.0
  "@crxjs/vite-plugin": 2.0.0
  "@cspell/cspell-types": 9.0.2
  "@cspell/eslint-plugin": 9.0.2
  "@eslint/compat": 1.3.0
  "@eslint/eslintrc": 3.3.1
  "@eslint/js": 9.28.0
  "@eslint/json": 0.12.0
  "@eslint/markdown": 6.5.0
  "@formkit/tempo": 0.1.2
  "@heroicons/react": 2.2.0
  "@hookform/resolvers": 5.1.1
  "@lerna-lite/cli": 4.3.0
  "@lerna-lite/publish": 4.3.0
  "@lerna-lite/version": 4.3.0
  "@next-auth/prisma-adapter": 1.0.7
  "@next/eslint-plugin-next": 15.3.3
  "@prisma/client": 6.9.0
  "@radix-ui/colors": 3.0.0
  "@radix-ui/react-aspect-ratio": 1.1.7
  "@radix-ui/react-avatar": 1.1.10
  "@radix-ui/react-form": 0.1.7
  "@radix-ui/react-progress": 1.1.7
  "@stitches/react": 1.2.8
  "@storybook/addon-docs": 9.1.0-alpha.6
  "@storybook/addon-essentials": 8.6.14
  "@storybook/addon-interactions": 8.6.14
  "@storybook/addon-links": 9.1.0-alpha.6
  "@storybook/addon-styling-webpack": 2.0.0
  "@storybook/blocks": 8.6.14
  "@storybook/nextjs": 9.1.0-alpha.6
  "@storybook/react": 9.0.9
  "@storybook/test": 8.6.14
  "@tailwindcss/forms": 0.5.10
  "@testing-library/jest-dom": 6.6.3
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@types/bcrypt": 5.0.2
  "@types/chrome": 0.0.326
  "@types/eslint-config-prettier": 6.11.3
  "@types/glob": 8.1.0
  "@types/jest": 29.5.14
  "@types/jsdom": 21.1.7
  "@types/mock-fs": 4.13.4
  "@types/node": 22.15.31
  "@types/react": 19.1.8
  "@types/react-dom": 19.1.6
  "@typescript-eslint/eslint-plugin": 8.34.0
  "@typescript-eslint/parser": 8.34.0
  "@typescript-eslint/utils": 8.34.0
  "@vanilla-extract/css": 1.17.4
  "@vanilla-extract/dynamic": 2.1.5
  "@vanilla-extract/next-plugin": 2.4.14
  "@vanilla-extract/webpack-plugin": 2.3.22
  "@vercel/postgres": 0.10.0
  "@vitest/ui": 3.2.3
  astro: 5.9.2
  autoprefixer: 10.4.21
  bcrypt: 6.0.0
  clsx: 2.1.1
  consola: 3.4.2
  cpx2: 8.0.0
  cspell: 9.0.2
  css-loader: 7.1.2
  dotenv: 16.5.0
  dotenv-cli: 8.0.0
  es-toolkit: 1.39.3
  esbuild: 0.25.5
  eslint: 9.28.0
  eslint-config-next: 15.3.3
  eslint-config-prettier: 10.1.5
  eslint-plugin-astro: 1.3.1
  eslint-plugin-import: 2.31.0
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-storybook: 9.1.0-alpha.6
  eslint-plugin-turbo: 2.5.4
  eslint-plugin-unicorn: 59.0.1
  eslint-plugin-unused-imports: 4.1.4
  eslint-plugin-yml: 1.18.0
  evp-ts: 1.1.1
  fs-extra: 11.3.0
  git-cz: 4.9.0
  glob: 11.0.3
  globals: 16.2.0
  jest: 30.0.0
  jest-environment-jsdom: 30.0.0
  jest-html-reporters: 3.1.7
  jotai: 2.12.5
  jsdom: 26.1.0
  mini-css-extract-plugin: 2.9.2
  msw: 2.10.2
  neverthrow: 8.2.0
  next: 15.3.3
  next-auth: 4.24.11
  node-fetch: 3.3.2
  npm-run-all2: 8.0.4
  pino: 9.7.0
  postcss: 8.5.5
  prettier: 3.5.3
  prisma: 6.9.0
  puppeteer: 24.10.1
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: 7.57.0
  react-lite-youtube-embed: 2.5.1
  react-tweet: 3.2.2
  recharts: 2.15.3
  renovate: 40.53.1
  schema-dts: 1.1.5
  serve: 14.2.4
  storybook: 9.1.0-alpha.6
  style-loader: 4.0.0
  tailwindcss: 4.1.10
  textlint: 14.8.0
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.2.2
  textlint-rule-no-todo: 2.0.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  ts-jest: 29.4.0
  tsconfig-paths-webpack-plugin: 4.2.0
  tsdown: 0.12.7
  tsup: 8.5.0
  tsx: 4.20.3
  turbo: 2.5.4
  type-fest: 4.41.0
  typescript: 5.8.3
  typescript-eslint: 8.34.0
  valibot: 1.1.0
  vercel: 43.1.0
  vite: 6.3.5
  vitest: 3.2.3
  webpack-merge: 6.0.1
  zod: 3.25.63
