packages:
  - "packages/*"
  - "packages/eslint-config/*"
  - "apps/*"

catalog:
  "@astrojs/react": 4.3.0
  "@crxjs/vite-plugin": 1.0.14
  "@cspell/eslint-plugin": 9.0.2
  "@eslint/compat": 1.2.9
  "@eslint/eslintrc": 3.3.1
  "@eslint/js": 9.28.0
  "@eslint/json": 0.12.0
  "@eslint/markdown": 6.5.0
  "@formkit/tempo": 0.1.2
  "@heroicons/react": 2.2.0
  "@next/eslint-plugin-next": 15.3.3
  "@storybook/addon-docs": 8.6.14
  "@storybook/addon-essentials": 8.6.14
  "@storybook/addon-interactions": 8.6.14
  "@storybook/addon-links": 8.6.14
  "@storybook/addon-styling-webpack": 2.0.0
  "@storybook/blocks": 8.6.14
  "@storybook/nextjs": 8.6.14
  "@storybook/react": 8.6.14
  "@storybook/test": 8.6.14
  "@tailwindcss/forms": 0.5.10
  "@testing-library/jest-dom": 6.6.3
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@types/bcrypt": 5.0.2
  "@types/chrome": 0.0.326
  "@types/eslint-config-prettier": 6.11.3
  "@types/glob": 8.1.0
  "@types/jest": 29.5.14
  "@types/jsdom": 21.1.7
  "@types/mock-fs": 4.13.4
  "@types/node": 22.15.29
  "@types/react": 19.1.6
  "@types/react-dom": 19.1.6
  "@typescript-eslint/eslint-plugin": 8.33.1
  "@typescript-eslint/parser": 8.33.1
  "@typescript-eslint/utils": 8.33.1
  "@vanilla-extract/next-plugin": 2.4.11
  "@vanilla-extract/webpack-plugin": 2.3.19
  "@vercel/postgres": 0.10.0
  "@vitest/ui": 3.2.1
  "astro": 5.8.2
  "autoprefixer": 10.4.21
  "bcrypt": 6.0.0
  "clsx": 2.1.1
  "consola": 3.4.2
  "cpx2": 8.0.0
  "dotenv": 16.5.0
  "es-toolkit": 1.38.0
  "esbuild": 0.25.5
  "eslint": 9.28.0
  "eslint-config-next": 15.3.3
  "eslint-config-prettier": 10.1.5
  "eslint-plugin-astro": 1.3.1
  "eslint-plugin-import": 2.31.0
  "eslint-plugin-react-hooks": 5.2.0
  "eslint-plugin-storybook": 0.12.0
  "eslint-plugin-turbo": 2.5.4
  "eslint-plugin-unicorn": 59.0.1
  "eslint-plugin-unused-imports": 4.1.4
  "evp-ts": 1.1.1
  "fs-extra": 11.3.0
  "glob": 11.0.2
  "globals": 16.2.0
  "jest": 29.7.0
  "jest-environment-jsdom": 29.7.0
  "jest-html-reporters": 3.1.7
  "jsdom": 26.1.0
  "mini-css-extract-plugin": 2.9.2
  "msw": 2.9.0
  "neverthrow": 8.2.0
  "next": 15.3.3
  "node-fetch": 3.3.2
  "npm-run-all2": 8.0.4
  "pino": 9.7.0
  "postcss": 8.5.4
  "prettier": 3.5.3
  "prisma": 6.9.0
  "puppeteer": 24.10.0
  "react": 19.1.0
  "react-dom": 19.1.0
  "recharts": 2.15.3
  "rolldown": 1.0.0-beta.11
  "serve": 14.2.4
  "storybook": 8.6.14
  "tailwindcss": 4.1.8
  "ts-jest": 29.3.4
  "tsconfig-paths-webpack-plugin": 4.2.0
  "tsdown": 0.12.7
  "tsup": 8.5.0
  "tsx": 4.19.4
  "typescript": 5.8.3
  "typescript-eslint": 8.33.1
  "valibot": 1.1.0
  "vercel": 42.3.0
  "vite": 6.3.5
  "vitest": 3.2.1
  "webpack-merge": 6.0.1
  "zod": 3.25.51
