# https://turborepo.org/docs/ci/github-actions
name: Userscript build by using turbo cache
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write

    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # build process
      - name: build userscript
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: yarn install and build
        run: |
          yarn install
          yarn build
        env:
          CI: true
          TURBO_TOKEN: ${{ secrets.USERSCRIPT_TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.USERSCRIPT_TURBO_TEAM }}
