# https://turborepo.org/docs/ci/github-actions
# https://kotaro7750.hatenablog.com/entry/dotfile_ci
name: Userscript build by using turbo cache
on: [push]

jobs:
  dotfiles:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        script: ["./packages/dotfiles/init/linux/scripts/zsh.sh", "./packages/dotfiles/init/linux/scripts/tmux.sh"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dotfiles
      run: ${{matrix.script}}

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write

    name: Build userscript
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # build process
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: yarn install
        run: yarn install

      - name: build
        run: yarn build
        env:
          CI: true
          TURBO_TOKEN: ${{ secrets.USERSCRIPT_TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.USERSCRIPT_TURBO_TEAM }}

      - name: test
        run: yarn test
        env:
          CI: true
          TURBO_TOKEN: ${{ secrets.USERSCRIPT_TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.USERSCRIPT_TURBO_TEAM }}