# https://turborepo.org/docs/ci/github-actions
# https://kotaro7750.hatenablog.com/entry/dotfile_ci
name: Userscript build by using turbo cache
on: [push]

jobs:
  dotfiles:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        script:
          [
            "./packages/dotfiles/init/linux/scripts/zsh.sh",
            "./packages/dotfiles/init/linux/scripts/tmux.sh",
          ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Install dotfiles
        run: ${{matrix.script}}

  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
    env:
      CI: true
      TURBO_TOKEN: ${{ secrets.USERSCRIPT_TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.USERSCRIPT_TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: test
        run: pnpm test
