# https://github.com/microsoft/windows-rs/blob/master/.github/workflows/
name: rust-action for Windows

on:
  push:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "apps/**"
      - "packages/**"
      - "**.js"
      - "pnpm**"
      - "package.json"
      - "renovate.json"
      - ".node-version"
      - ".npmrc"

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cargo_check:
    name: Check
    strategy:
      matrix:
        rust: [stable]
        runs-on:
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Check
        run: cargo check
